version: "3.9"
services:
  firestore_emulator:
      image: mtlynch/firestore-emulator
      environment:
          - FIRESTORE_PROJECT_ID=${REACT_APP_PROJECT_ID}
          - PORT=8200
  app:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - NETLIFY_AUTH_TOKEN=${NETLIFY_AUTH_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "8888:8888"
  depends_on:
      - firestore_emulator
      