version: "3.9"
services:
  web:
    container_name: memorize_words
    image: williamjackson/netlify-cli
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - NETLIFY_AUTH_TOKEN=${NETLIFY_AUTH_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run dev"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:8888"
      